### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by djstarr** [mkormendy/homebridge-node-alarm-dot-com#1]
This project is awesome to remove the wrapapi dependency. Also love that the individual sensors show up in Home.app. Am seeing the sensors but the sensor states don’t seem to update in Home.app, eg when I open a door or window. Happy to help debug.

**Comment by mkormendy** [comment]
@djstarr I'll definitely look into this as I have the same issue. Can you list the number and types of sensors you have (motion-sensor, contact-sensor, and leak-sensor)? I only have motion and contact sensors, but it'd be nice to test with the leak one as well.

**Comment by mkormendy** [comment]
Cross-posted from 
https://github.com/mkormendy/node-alarm-dot-com/issues/2

**Comment by nelhenry** [comment]
Thanks for your work on this. I have a smoke detector, glass break, 3 door sensors and 2 keyfobs all showing up in HomeKit now. Status does not report, but it’s promising to have them appear at all.

**Comment by djstarr** [comment]
@mkormendy I have 1 motion sensor and it appears to be working, properly showing as motion detected in Home.app. I also have 4 groups of window/door contact sensors, 1 keypad, 1 group of glass break sensors, and 1 carbon monoxide detector.

**Comment by mkormendy** [comment]
@djstarr well that's good news! I have motion sensors and they are not reporting motion detected, so I am wondering if there's a delay. How long did it take for the system to report the motion on your Home app?

**Comment by djstarr** [comment]
@mkormendy Now that I’m looking at it more closely, I think it’s just perpetually detecting motion. Doesn’t seem to reset. Turned on notifications to see if I can better monitor activity.

**Comment by amitgandhinz** [comment]
@mkormendy awesome work on this!  Ive got it running, and the panel arming states appear to be working now (Yay!).  It is also detecting my sensors (Motion Detectors, Door Sensors, Glass Break Sensors) which is pretty cool.  However, those sensors don't appear as accessories in the Home App.    I also get a number of 'Warning: Sensor with unknown state 0' being logged every minute for each sensor.

**Comment by mkormendy** [comment]
@djstarr let me know!

**Comment by mkormendy** [comment]
@amitgandhinz you say that it is "detecting" your sensors, but "they don't appear as accessories" in the Home App. What do you mean by "detecting"?

**Comment by amitgandhinz** [comment]
@mkormendy by detecting, I mean that when home bridge starts up, I see in the logs things like `Added sensor Back Door`, etc.  This is however immediately followed by the `Warning: Sensor with unknown state 0`.  Once homebridge is fully started up, I continue to get the Warning messages.

**Comment by mkormendy** [comment]
@amitgandhinz please open a separate issue for the problems you are experiencing. This issue thread deals with sensors showing up in the Home app but their states not updating.

**Comment by amitgandhinz** [comment]
created https://github.com/mkormendy/homebridge-node-alarm-dot-com/issues/4 for my issue

**Comment by bryantcoles** [comment]
I confirm the same behavior as @djstarr mentions. The motion sensor perpetually reports motion detected.

**Comment by djstarr** [comment]
Ok, have a little more detail. The motion sensor isn’t perpetually detecting motion. It just seems that the delay to reset the sensor is so long that I still haven’t “seen” it. But it was reset over night and walking out to our main living area triggered within a couple of seconds. It may also be staying on given the motion sensor is in the main open living area of our first floor. One last note is that I’m living on the latest iOS 12 betas. Am still not entirely sure what additional data would be useful to you but I’ll share what I can.

**Comment by bryantcoles** [comment]
Not on my main phone, but im ready to make the jump. Is HomeKit rock solid on the latest beta? I have a very large HomeKit setup and wanted to certain before I make the jump.

**Comment by mkormendy** [comment]
For the first time I chose not to do the beta program, so I am not sure, but I think the public release is coming out in a week's time to coincide with the reveal of the new iPhone, so I'm going to wait for that before I update to 12.

**Comment by djstarr** [comment]
Have been on iOS 12 since beta 1 and same for macOS 10.14 Mojave (which includes Home.app). No major issues with the homebridge setup. YMMV.

**Comment by mkormendy** [comment]
Update, it's odd, I've now been getting notifications about my door contact sensors that doors were open and closed exactly when they happened.
However I'm still not getting the notifications of movement from my motion sensors.
Not sure why or how they started working, since I haven't actually made any updates or changes to the code on my live homebridge setup.

**Comment by mkormendy** [comment]
After some testing, I have come to what I feel is an unfortunate conclusion.

My testing can confirm that the sensor states are being detected correctly, and homebridge does poll for them, and they DO show up.  However, the fact of the matter is that alarm.com website, nor the mobile app, don't report the events fast enough before they get deactivated.

The test case I used was at my entrance where I have a door contact sensor, and a motion sensor as well.

Opening the front door took anywhere from 45secs-1.5mins to report to the website api that the state has changed to 'Open'. Add the addition polling time  that is either built into the Home.app or into homebridge to query states of accessories (could be anywhere  up to 30secs). I know this because I left the app open while waiting and had my stopwatch on my watch counting until the icon changed with a little animation of the contact sensor being triggered.
This worked as well when I closed the door and about a minute and a half later the door contact sensor showed as closed.

The motion sensors are another story, and the data object received from alarm.com always showed the state of the sensor as 'Idle', and never anything else. I also noticed that my motion sensors (wired only) have a red light that shows that it detected motion. This light would never stay on for longer than roughly 3 seconds before going off for a second and then back on again - regardless of my still constantly making considerable motion and never stopping.

My keypad screen, which just so happens to be at the front entrance too, did register my motion on the screen and that the system was actively 'Open', however the second I saw that state on the keypad, I then immediately queried the interface and received no change.

It seems that the motion sensors themselves are only allowed to report motion for a short time, and that signal gets sent to the keypad to register that the system is open then quickly closed again, and then open again.
At the same time, I'm sure the motion sensor trigger sends a signal to the cellular modem in the alarm.com panel, connecting to the alarm.com servers, and reporting what the system detected.

This is never real-time for me. My mobile app doesn't actively report motion in the history panel. However the history panel does register it eventually (2 minutes or more), but so late in time that it's useless, and reset or made idle again before the json object gets updated on the website API that I poll with the node interface I built.

It's of note that I have top tier fiber internet, so my internet speed is ludicrous and never laggy.

I thought about adding a poll timer to poll more frequently like every 5 seconds or 10 seconds, but no matter how short between polls I made to the alarm.com server, I could never get the motion sensor to be anything but 'Idle'. I think this is an inherent result of the entire Alarm.com network/connectivity setup.

That being said, I am going to close this ticket as unresolved unless something improves or someone sheds light about my misinterpretation of the setup and the resulting code.

**Comment by twentyNoise** [comment]
@mkormendy oddly enough I too received my first status change this morning around 9:30 am PST. I had installed your updated plugin this past week and was getting excited by the inclusion of all my sensors in HomeKit etc., albeit them not updating yet. Then yesterday I enabled a Status notification in the Home app for our Front Door. Well I received a notification that the door was opened and then another when it was closed. I wasn’t home at the time so I can’t say what sort of latency there was but still strange that all of a sudden I received a notification. But I didn’t receive any yesterday and the Front Door was opened / closed multiple times. I’m going to enable a few other notifications and see what happens.

In any case this definitely puts the effectiveness of these sensors / HomeKit into question.

The one thing I’ll add is that my notifications from the Alarm.com app are typically pretty immediate, at least they are for my outdoor motion sensors triggering a iOS notification. I’ll do some more tests when I can.

Thanks for all your work on this!

**Comment by mkormendy** [comment]
I've noticed that the Alarm.com app Push Notifications are delayed anywhere from 5 seconds to 1 minute on my system. This means that the communication from the panel to Alarm.com servers to the Apple Notification Servers (which handle push notifications) are even delayed before they reach the phone Alarm.com app.

Unfortunately we can't listen in on those specific push notifications to the app because they are encrypted from the Apple Servers to the Alarm.com app on the phone with SSL certs. So we are relegated to waiting for the Alarm.com website to update it's sensor states which is slow.

**Comment by twentyNoise** [comment]
Is there a way to stop the plugin from creating the HomeKit sensors (based on the sensors I have)? That is, since mine are never updating (rarely the Front Door updates)  they're just taking up lots of space in my Home App. Or do you still plan on figuring out how to get them to update more consistently?

Thanks!

**Comment by mkormendy** [comment]
I ended up cutting a huge cedar tree down this past weekend, but initially planned to spend time implementing a couple user-configuration options to hide messages in the log as well as hide different sensor accessories since some of them don't update.

I have actually had more reliability with the contact sensors lately. They let me know that a door is open or closed consistently now, albeit a little less-immediate, they do actually fire-off nonetheless.

**Comment by twentyNoise** [comment]
I see. Good to know.

Any ideas why the Contact sensor notifications would be sporadic?

**Comment by twentyNoise** [comment]
No, the Alarm.com app is pretty consistent. I’ve testing the front door sensor specifically and I will always receive a notification from the Alarm.com app and only sometimes from the Home App.

Also, what is the purpose of the Homebridge plugin logging in to Alarm.com every 10 minutes? Is this the temporary polling that you have in place? If it’s only polling every 10 minutes then how are certain things like an System Armed command sent immediately (if we’re in the middle of the 10 minute pause)? It seems like ‘any’ status change would update and not just system arming actions etc.

**Comment by mkormendy** [comment]
I've got some testing to do myself and I've made a list of different scenarios.

Did you manage to see if the notifications show up for your door if you open it long enough?

**Comment by twentyNoise** [comment]
I tested it a bit. Like you found it’s not good news.

Some general notes:

Alarm.com App Notifications:
- Not precise. Held the front door open for 3 minutes and it didn’t register in the App for at least a few minutes. And it’s worse because it timestamps it at the time of the notification and not the actual time. But I swear sometimes it’s more accurate. I’ll test some more this evening.
- These seem to at least be consistent in that if an event ‘happens’ it is recorded, or I am notified.

HomeKit
- Held the door open for 3 minutes and closed, never received a HomeKit notification.

Again, I’ll test more this evening but if it ends up that these aren’t fairly reliable I’ll end up just using the panel arm / disarm functions with Homebridge and hide the rest.

I’m interested to see what else you find.
