### ISSUE TITLE
Panel disappearing from Homekit scenes

### ISSUE THREAD

**Issue by jnanes** [mkormendy/homebridge-node-alarm-dot-com#10]
I have noticed recently, every few days, scenes that include my Alarm Panel, will randomly show the panel missing  from the scene. When I check Homekit, the panel is there and I can simply re-add it to the scene. This has been occurring often. Any ideas?

**Comment by mkormendy** [comment]
I have not had this issue whatsoever, but I would like to know the setup you have at home?

What is your Homebridge running on? (eg. MacOS, some Raspberry Pi variant with Linux, a Windows system)
What is your Homekit Hub running as? (Apple TV or iPad, including model + os)

I am currently running my stuff on an older 2011 Mac Mini with High Sierra and Homebrew installed node.js v10.
My Homekit hub is running as one of three Apple TV 4Ks with the latest TVOS 12. I have a backup iPad Air with iOS12 as well, but it never gets a chance to run as the hub because the Apple TVs prioritize first.

I also have my wireless network running off of a Ubiquity ACPRO AP.

**Comment by jnanes** [comment]
Thanks for your reply. 


What is your Homebridge running on? (eg. MacOS, some Raspberry Pi variant with Linux, a Windows system) Ubuntu 16.04 LTS running in a VM on ESXi
What is your Homekit Hub running as? (Apple TV or iPad, including model + os) ATV 4, 12.0.1

Wifi - Unifi AC-M - 2 mesh points, the apple TV is connected to the main, wired mesh point.

**Comment by mkormendy** [comment]
No obvious answers, but for the time being, I'm looking into this:

https://github.com/nfarina/homebridge/issues/570

**Comment by jnanes** [comment]
Also - I just noticed this in the logs each time homebridge launches, it seems all my sensors are re-adding each time homebridge launches?

**Comment by jnanes** [comment]
0|homebrid | [2018-11-3 20:41:50] [Security System] Added sensor Master Bathroom Window (95650268-4)
0|homebrid | [2018-11-3 20:41:50] [Security System] Master bedroom Window 1 (95650268-5) removed from HomeBridge.
0|homebrid | [2018-11-3 20:41:50] [Security System] Adding Contact Sensor "Master bedroom Window 1" (id=95650268-5, uuid=49fb5ba9-572f-41fd-b48e-69c954f1225e)
0|homebrid | [2018-11-3 20:41:50] [Security System] Updating sensor 95650268-5, state=0, prev=null
0|homebrid | [2018-11-3 20:41:50] [Security System] Added sensor Master bedroom Window 1 (95650268-5)
0|homebrid | [2018-11-3 20:41:50] [Security System] Master bedroom Window 2 (95650268-6) removed from HomeBridge.
0|homebrid | [2018-11-3 20:41:50] [Security System] Adding Contact Sensor "Master bedroom Window 2" (id=95650268-6, uuid=34760e81-59a6-4aab-a1a8-2c25e534a0c6)
0|homebrid | [2018-11-3 20:41:50] [Security System] Updating sensor 95650268-6, state=0, prev=null
0|homebrid | [2018-11-3 20:41:50] [Security System] Added sensor Master bedroom Window 2 (95650268-6)
0|homebrid | [2018-11-3 20:41:50] [Security System] Side Garage Door (95650268-3) removed from HomeBridge.
0|homebrid | [2018-11-3 20:41:50] [Security System] Adding Contact Sensor "Side Garage Door" (id=95650268-3, uuid=4eb636e6-580c-4f0b-9017-44955507d925)
0|homebrid | [2018-11-3 20:41:50] [Security System] Updating sensor 95650268-3, state=0, prev=null
0|homebrid | [2018-11-3 20:41:50] [Security System] Added sensor Side Garage Door (95650268-3)

**Comment by mkormendy** [comment]
How often do you launch Homebridge? Once set up, I never really re-launch Homebridge. The plugin is designed to rescan for devices and rebuild them on launch - so this is expected behavior.

**Comment by jnanes** [comment]
My VM is scheduled to reboot weekly just for housekeeping, I was having a weird issue that I thought the reboot was helping with but I can stop at it if you think it’s best. I changed my launch method to PM2 which seems to handle homebridge a lot better

Thanks,
Jesse

**Comment by mkormendy** [comment]
I have some further questions now. But I'm not sure if you're still experiencing this issue. Please let me know. I've seen on some subreddits that Homekit has been buggy, losing devices like you are experiencing and then people are either re-adding them or come to them at a later time when they've reappeared on their own. I'll try to link an article the next time I come across it again.

In the meantime could you answer the following?

1. Could you resolve that this is not happening just because you are rebooting it each week?
2. I've never needed PM2 to handle homebridge, so I have no way to test if that's the issue.
3. What version of node and homebridge are you using?

**Comment by mkormendy** [comment]
Since I ported jhurliman's repo to my plugin, and after having some time to really look at the code. I've realized that this plugin actually is designed to re-add themselves at each startup. Further investigation reveals that this is done to recognize the addition of more sensors and to also re-sync/refresh the current ones in case any of them aren't reporting their state correctly.

I'm going to close this, as I can't reproduce the loss of the panel on my system and I haven't heard back from the OP.
