### ISSUE TITLE
Sensors detected, but Homekit Accessories not added

### ISSUE THREAD

**Issue by amitgandhinz** [mkormendy/homebridge-node-alarm-dot-com#4]
When starting up homebridge, my sensors are being detected (as I see `Added sensor Back Door` in the logs).  However, this is always followed by a `Warning: Sensor with unknown state 0`.  Subsequently, an accessory is not created for the sensor.

Upon investigating the code, I believe the issue lies here https://github.com/mkormendy/homebridge-node-alarm-dot-com/blob/master/index.js#L250 where the getSensorType returns an unknown type. 

I am not sure if this is also related, but I noticed on my alarm.com portal I currently do not have the options to turn sensor activity monitoring on/off.

**Comment by mkormendy** [comment]
Amit, please join me on Slack and lets work through this.
https://join.slack.com/t/homebridge-nodeadc/shared_invite/enQtNDI5ODA3Njg2Mjk0LTI1NWMxMTc5ZGFkMjUxYjMyNmI0YmVjMWRhMTBiNWI5NmVmMjBmNDE2MTVmZjkwODNhZmY5NmQyN2UwNDAxNzQ

**Comment by mkormendy** [comment]
@Amit Gandhi go to the history on your mobile app and see if you have any entries that have any Motion Activated/Restored messages in your list. If you don’t, than your account isn’t set up for sensor activity monitoring and you’ll need to speak with your installer/provider about changing that on your account.

**Comment by mkormendy** [comment]
I wonder if I can check the alarm systems to see what package-type is applied, and if there's a package code on the system, then I can provide some logic to avoid attempting to add accessories, and also provide a help message, noting this in the logs.

**Comment by mkormendy** [comment]
@amitgandhinz have you upgraded your package? If not I would like to see if we can do some interactive testing of the output from Alarm.com.

**Comment by amitgandhinz** [comment]
Im in the process of having it upgraded (called them yesterday since my contract period just ended/renewed).  It doesn't look like they have processed the upgrade yet though.

**Comment by mkormendy** [comment]
@amitgandhinz if I could ask, how many options did you have for the different packages they were offering you to upgrade to?

**Comment by amitgandhinz** [comment]
In terms of packages, there’s basic and interactive.  Here’s a good comparison from another company of the two levels: https://suretydiy.com/product/monthly-alarm-monitoring/

**Comment by mkormendy** [comment]
Yeah there's a slight delay, as expected, since there's no real push-notification system in place to have real-time updates.

Thanks for the package examples. I've got some other users with setups that are also having some problems with the sensors.
I'm hoping to find some time to work on cleaning up and taking a stab at speeding things up somehow.

**Comment by kcharwood** [comment]
It would be helpful to add a config value that allows me to disable it, so it doesn't clutter the logs while also not requiring me to turn the logs all the way down to error only.

**Comment by mkormendy** [comment]
@amitgandhinz and @kcharwood I have added a new option that allows you to hide/ignore accessories on a per item basis. After doing some more research, it's been difficult to determine the type of package that a user may have on their account. This is likely due to the way that they sell their services through different proxy-providers like ADT, FrontPoint, etc.  This should help hide the unusable devices from Homekit. Beyond this feature, any further granularity is out of scope of a public-ready feature set and I recommend crafting your own personal iteration of it for your own selective use.
